### PR TITLE
Fix for ordering issues

### LINKED ISSUE #45: The ID mappings and the sequences are no longer sorted
Up to version 7.0 of RNACentral, we could assume that the files `id_mapping.tsv` and `rnacentral_species_specific_ids.fasta` contained the entries in the same order (the mapping had several lines per entry, but always grouped). This made possible to iterate both files at the same time to compare their info: in [entries.scala#L8](https://github.com/ohnosequences/db.rnacentral/blob/master/src/main/scala/entries.scala#L8) we did the following, which basically yields pairs of (sequence, id mapping), iterating the files in order:

```scala
(sequences parseFrom data) zip (IDMapping entryAnnotationsByRNAIDOrErrors data)
```

But from the 8th release of RNACentral, the fasta sequences are not ordered (it seems the mappings are still ordered by their ID), so a simple zip between the iterators of sequences and the ID mappings is not enough.

We need to iterate the sequences and look for that specific RNA ID in the ID mappings, so we can retrieve the annotations information.

### PR DESCRIPTION
**Pull request by agarciamontoro**
Although it is still untested, this is an attempt to fix #45. I'll update this info when I test it from `db.rna16s` with the newer latest versions of RNACentral.

Closes #45.

### CODE REVIEW

**Comment by agarciamontoro** [comment]
I just tested this with a subset of the mappings (only the first five million lines) and it seems to work smoothly. I'm merging this as soon as I can properly test it with the whole mappings file in an AWS instance (my humble machine struggle with parsing the whole file).

**Comment by eparejatobes** [comment]
Some release tests are bound to fail now (idempotent parsing/serialization comes to mind). Apart from that, let's make a release and see if we can make db.rna16s work ASAP.

**Comment by agarciamontoro** [comment]
Tested with db.rna16s (locally, nothing in S3 yet) and everything works as expected.

> Some release tests are bound to fail now (idempotent parsing/serialization comes to mind).

I'm checking this now.

**Comment by agarciamontoro** [comment]
The only tests that presented any problem:

- `SequencesAndIDMapping` suite: I removed it because it was not a real test (it had no assert and it always passed regardless of the data) and if it were a real test it would always fail because it tested that the sequences and mappings were aligned (they are no longer aligned from version 8.0). What we can do later is to check that all IDs from the fasta file are actually in the id mappings file.
- `idempotent parsing/serialization`: it tests parsing/serialization of only the sequences, so it passes.
- `parsing and integrity` from `Sequences`: it had no assert either, I fixed that and it still passes.
- `parse all EntryAnnotations` from `IDMapping`: some databases missing for v9.0; this is fixed by #43.
- `parse all` from `Entries`: it fails because of the missing databases; this is fixed by #43.

So: we can merge this, release it even if all tests do not pass, use it from `db.rna16s` and wait for #43 to fix everything else. Do you agree, @eparejatobes?

**Comment by eparejatobes** [comment]
:+1:

**Pull request merged**
