### PR TITLE
Multiple versions and local file mirroring

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
Note to self: integrate ohnosequences/s3 and ohnosequences/files once ready.

**Comment by agarciamontoro** [comment]
> Note to self: integrate ohnosequences/s3 and ohnosequences/files once ready.

We can do it now, I guess it will be easier.

**Comment by agarciamontoro** [comment]
Oops, I understood that you wanted to fuse both repos. Nevermind.

**Comment by eparejatobes** [comment]
I'm merging this as-is; I want to integrate api.rnacentral ASAP.

**Pull request merged**
